### ISSUE TITLE
채널 상태 가져오기 Error catch, UI 구현

### ISSUE THREAD

**Issue by So-chiru** [wakscord/extension#9]
현재 채널 상태 가져오기가 실패하였을때 처리하는 UI나 로직이 없는데 있으면 유저 입장에서 혼란도 없을 것 같고 좋을 것 같습니다

**Comment by minibox24** [comment]
https://github.com/wakscord/extension/blob/ab99f160ba3fe5041aa430f4a221048bef4876cf/src/App.tsx#L69

여기 구현되어 있습니다!!

**Comment by So-chiru** [comment]
이런 그렇군요 try catch만 보고 비어 있어서 없는 줄 알았스빈다...
